import { DataType } from './typings.ts';

export const data: DataType[] = [
  {
    key: '1',
    name: '阿苯达唑胶囊',
    category: '甲类',
    price: '3.40-23.00',
    tags: ['化学药品', '医保甲类', '甲类非处方药(OTC)'],
    application: '用于蛔虫病、绕虫病',
  },
  {
    key: '2',
    name: '阿苯达唑咀嚼片',
    category: '甲类',
    price: '3.66-13.00',
    tags: ['化学药品', '医保甲类', '甲类非处方药(OTC)'],
    application: '用于治疗钩虫、蛔虫、鞭虫、绕虫、施毛虫等线虫病,也可治疗囊虫和包虫病',
  },
  {
    key: '3',
    name: '阿苯达唑颗粒',
    category: '甲类',
    price: '2.13-13.60',
    tags: ['化学药品', '医保甲类', '甲类非处方药(OTC)'],
    application: '用于治疗钩虫、蛔虫、鞭虫、绕虫、施毛虫等线虫病,也可治疗囊虫和包虫病',
  },
  {
    key: '4',
    name: '阿苯达唑片',
    category: '甲类',
    price: '3.00-10.00',
    tags: ['化学药品', '医保甲类', '甲类非处方药(OTC)'],
    application: '用于治疗钩虫、蛔虫、鞭虫、绕虫、施毛虫等线虫病,也可治疗囊虫和包虫病',
  },
  {
    key: '5',
    name: '阿卡波糖胶囊',
    category: '甲类',
    price: '27.00-146.00',
    tags: ['化学药品', '医保甲类', '处方药(Rx)'],
    application: '用于配合饮食控制治疗糖尿病',
  },
  {
    key: '6',
    name: '阿卡波糖咀嚼片',
    category: '甲类',
    price: '80.50-80.70',
    tags: ['化学药品', '不在医保药品目录', '处方药(Rx)'],
    application: '用于治疗糖尿病、降低糖耐量低减者的餐后血糖',
  },
  {
    key: '7',
    name: '阿卡波糖片',
    category: '甲类',
    price: '42.00-141.58',
    tags: ['化学药品', '医保甲类', '处方药(Rx)'],
    application: '用于治疗糖尿病、降低糖耐量低减者的餐后血糖',
  },
  {
    key: '8',
    name: '阿立哌唑胶囊',
    category: '甲类',
    price: '61.55-71.00',
    tags: ['化学药品', '医保甲类', '处方药(Rx)'],
    application: '用于治疗精神分裂症',
  },
  {
    key: '9',
    name: '阿立哌唑口崩片',
    category: '甲类',
    price: '',
    tags: ['化学药品', '医保甲类', '处方药(Rx)'],
    application: '用于治疗精神分裂症',
  },
  {
    key: '10',
    name: '阿立哌唑片',
    category: '甲类',
    price: '85.00-200.00',
    tags: ['化学药品', '医保甲类', '处方药(Rx)'],
    application: '用于治疗精神分裂症',
  },
  {
    key: '11',
    name: '阿莫西林肠溶片',
    category: '甲类',
    price: '',
    tags: ['化学药品', '不在医保药品目录', '处方药(Rx)'],
    application: '',
  },
  {
    key: '12',
    name: '阿莫西林分散片',
    category: '甲类',
    price: '2.67-12.80',
    tags: ['化学药品', '不在医保药品目录', '处方药(Rx)'],
    application: '用于敏感菌所所致呼吸道感染、泌尿道感染、胃肠道感染、皮肤和软组织感染',
  },
  {
    key: '13',
    name: '阿莫西林分散片',
    category: '甲类',
    price: '2.67-12.80',
    tags: ['化学药品', '不在医保药品目录', '处方药(Rx)'],
    application: '用于敏感菌所所致呼吸道感染、泌尿道感染、胃肠道感染、皮肤和软组织感染',
  },
];
